"""Added pincode to ParkingLot

Revision ID: 8d9a9b79e2cb
Revises: 
Create Date: 2025-07-26 00:24:18.491232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9a9b79e2cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.Integer(), nullable=False))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('vehicle_number')

    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
