"""Add duration field in reservation

Revision ID: d42004ac9e7f
Revises: 8d9a9b79e2cb
Create Date: 2025-07-30 22:23:39.544450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42004ac9e7f'
down_revision = '8d9a9b79e2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
